/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IBinanceBunksMarket,
  IBinanceBunksMarketInterface,
} from "../IBinanceBunksMarket";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "punkIndexToAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBinanceBunksMarket__factory {
  static readonly abi = _abi;
  static createInterface(): IBinanceBunksMarketInterface {
    return new utils.Interface(_abi) as IBinanceBunksMarketInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBinanceBunksMarket {
    return new Contract(address, _abi, signerOrProvider) as IBinanceBunksMarket;
  }
}
