/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPegSwap, IPegSwapInterface } from "../IPegSwap";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "source",
        type: "address",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "swap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPegSwap__factory {
  static readonly abi = _abi;
  static createInterface(): IPegSwapInterface {
    return new utils.Interface(_abi) as IPegSwapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPegSwap {
    return new Contract(address, _abi, signerOrProvider) as IPegSwap;
  }
}
