/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ILinkSwapperInterface extends ethers.utils.Interface {
  functions: {
    "getLinkAmountOut(uint256)": FunctionFragment;
    "getPairAddress(address)": FunctionFragment;
    "getWBNBAmountIn(uint256)": FunctionFragment;
    "setBeebitContract(address)": FunctionFragment;
    "swap(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLinkAmountOut",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getWBNBAmountIn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBeebitContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLinkAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPairAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWBNBAmountIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBeebitContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;

  events: {};
}

export class ILinkSwapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ILinkSwapperInterface;

  functions: {
    getLinkAmountOut(
      _inputWBNB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPairAddress(
      factory: string,
      overrides?: CallOverrides
    ): Promise<[string] & { pair: string }>;

    getWBNBAmountIn(
      _linkAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setBeebitContract(
      _newBeebit: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swap(
      _deadline: BigNumberish,
      _linkAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getLinkAmountOut(
    _inputWBNB: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPairAddress(factory: string, overrides?: CallOverrides): Promise<string>;

  getWBNBAmountIn(
    _linkAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setBeebitContract(
    _newBeebit: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swap(
    _deadline: BigNumberish,
    _linkAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getLinkAmountOut(
      _inputWBNB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPairAddress(factory: string, overrides?: CallOverrides): Promise<string>;

    getWBNBAmountIn(
      _linkAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBeebitContract(
      _newBeebit: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    swap(
      _deadline: BigNumberish,
      _linkAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getLinkAmountOut(
      _inputWBNB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPairAddress(
      factory: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWBNBAmountIn(
      _linkAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBeebitContract(
      _newBeebit: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swap(
      _deadline: BigNumberish,
      _linkAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLinkAmountOut(
      _inputWBNB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPairAddress(
      factory: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWBNBAmountIn(
      _linkAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBeebitContract(
      _newBeebit: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swap(
      _deadline: BigNumberish,
      _linkAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
